package com.example.demo;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.BeforeAll;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class Lab3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  protected static ThreadLocal<RemoteWebDriver> drivers = new ThreadLocal<RemoteWebDriver>();
  public static String remote_url = "http://localhost:4444";
  private void mylogin(){
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[1]/div/div/input")));
    }
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[1]/div/div/input")).clear();
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[2]/div/div/input")).clear();
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[1]/div/div/input")).sendKeys("x1761270349@gmail.com");
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[2]/div/div/input")).sendKeys("password");
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[7]/button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/a")));
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/a"));
      assert(elements.size() > 0);
    }
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }

  @BeforeAll
  static void setupClass() {
    WebDriverManager.chromedriver().setup();
  }

  @Before
  public void setUp() throws MalformedURLException {
    vars = new HashMap<String,Object>();
    //ChromeOptions options = new ChromeOptions();
    /*FirefoxOptions options = new FirefoxOptions();
    options.setPageLoadStrategy(PageLoadStrategy.NORMAL);
    drivers.set(new RemoteWebDriver(new URL(remote_url), options));
    drivers.get().get("http://pikabu.ru/");
    drivers.get().manage().timeouts().pageLoadTimeout(5, TimeUnit.SECONDS);
    driver = getDriver();*/
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  public WebDriver getDriver() {
    return drivers.get();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logout() {
    driver.get("https://pikabu.ru/");
    mylogin();
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[2]/div[2]")));
    }
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[2]/div[2]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[3]/div/div/div[1]/div[2]/button[1]")));
    }
    driver.findElement(By.xpath("//html/body/div[3]/div/div/div[1]/div[2]/button[1]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[7]/button")));
    }
  }
  @Test
  public void deleteBlogInDraft() {
    driver.get("https://pikabu.ru/");
    mylogin();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[1]/div/div[1]/aside/div[2]/a[1]")));
    }
    driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/aside/div[2]/a[1]")).click();
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div/div[1]/div[1]/button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[3]/div/div[1]/div/div[1]/div/button")));
    }
    vars.put("oldcount", driver.findElements(By.xpath("//html/body/div[3]/div/div[1]/div/div[2]/div/div")).size());
    System.out.println("Old count: "+vars.get("oldcount").toString());
    vars.put("oldcount", js.executeScript("return parseInt(arguments[0])-1", vars.get("oldcount")));
    driver.findElement(By.xpath("//html/body/div[3]/div/div[1]/div/div[2]/div/div[1]/div[1]/div[3]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[3]/div[2]/div/div/footer/button[1]")));
    }
    driver.findElement(By.xpath("//html/body/div[3]/div[2]/div/div/footer/button[1]")).click();
    vars.put("newcount", driver.findElements(By.xpath("//html/body/div[3]/div/div[1]/div/div[2]/div/div")).size());
    System.out.println("New count:" + vars.get("newcount").toString());
    vars.put("newcount", js.executeScript("return parseInt(arguments[0])", vars.get("newcount")));
    assertEquals(vars.get("newcount").toString(), vars.get("oldcount").toString());
  }
  @Test
  public void profile() {
    driver.get("https://pikabu.ru/");
    mylogin();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/a"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/a")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div/div[2]/main/div/div[2]/form/section/div[2]/div/h1/a")));
    }
    driver.findElement(By.xpath("/html/body/div[1]/div/div[2]/main/div/div[2]/form/section/div[2]/div/div[1]/section/div/textarea")).sendKeys("new info");
  }

  @Test
  public void search() {
    driver.get("https://pikabu.ru/");
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/header/div[2]/div/div/div[3]/div/div[1]/form/button")));
    }
    driver.findElement(By.xpath("//html/body/div[1]/header/div[2]/div/div/div[3]/div/div[1]/form/button")).click();
    driver.findElement(By.xpath("//html/body/div[1]/header/div[2]/div/div/div[3]/div/div[1]/form/div/input[1]")).sendKeys("Игры");
    driver.findElement(By.xpath("//html/body/div[1]/header/div[2]/div/div/div[3]/div/div[1]/form/button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div/div[2]/main/div/form/div[1]/section[1]/span[2]/input")));
    }
  }
  @Test
  public void subscription() {
    driver.get("https://pikabu.ru/");
    mylogin();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div/div[1]/aside/div[1]/div[1]/div/div[2]/div[1]/a")));
    }
    driver.findElement(By.xpath("//html/body/div[1]/div/div[1]/aside/div[1]/div[1]/div/div[2]/div[1]/a")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div/div[2]/main/div[1]/div/section/div[5]/div")));
    }
    try {
      Thread.sleep(2000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    vars.put("oldcount", driver.findElements(By.xpath("//html/body/div[1]/div/div[2]/main/div[1]/div/section/div[5]/div/div/span")).size());
    System.out.println("Old count: "+vars.get("oldcount").toString());
    vars.put("oldcount", js.executeScript("return parseInt(arguments[0])+1", vars.get("oldcount")));
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/header/div[2]/div/div/div[2]/div/div[4]/a")));
    }
    driver.findElement(By.xpath("//html/body/div[1]/header/div[2]/div/div/div[2]/div/div[4]/a")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div/div[2]/main/div/section[2]/div[1]/div/span/button[1]")));
    }
    driver.findElement(By.xpath("//html/body/div[1]/div/div[2]/main/div/section[2]/div[1]/div/span/button[1]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div/div[1]/aside/div[1]/div[1]/div/div[2]/div[1]/a")));
    }
    driver.findElement(By.xpath("//html/body/div[1]/div/div[1]/aside/div[1]/div[1]/div/div[2]/div[1]/a")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div/div[2]/main/div[1]/div/section/div[5]/div")));
    }
    vars.put("newcount", driver.findElements(By.xpath("//html/body/div[1]/div/div[2]/main/div[1]/div/section/div[5]/div/div/span")).size());
    System.out.println("New count:" + vars.get("newcount").toString());
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    vars.put(vars.get("newcount").toString(), js.executeScript("return parseInt(arguments[0])", vars.get("newcount")));
    assertEquals(vars.get("newcount").toString(), vars.get("oldcount").toString());
  }
  @Test
  public void unsubscription() {
    driver.get("https://pikabu.ru/");
    mylogin();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/header/div[2]/div/div/div[2]/div/div[4]/a")));
    }
    driver.findElement(By.xpath("//html/body/div[1]/header/div[2]/div/div/div[2]/div/div[4]/a")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div/div[2]/main/div/section[1]/div/a[2]")));
    }
    driver.findElement(By.xpath("//html/body/div[1]/div/div[2]/main/div/section[1]/div/a[2]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div/div[2]/main/div/section[2]/div[1]/div/span/button[1]")));
    }
    vars.put("oldcount", driver.findElements(By.xpath("//html/body/div[1]/div/div[2]/main/div/section[2]/div")).size());
    driver.findElement(By.xpath("//html/body/div[1]/div/div[2]/main/div/section[2]/div[1]/div/span/button[1]")).click();
    System.out.println("Old count: "+vars.get("oldcount").toString());
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    vars.put("newcount", driver.findElements(By.xpath("//html/body/div[1]/div/div[2]/main/div/section[2]/div")).size());
    vars.put("newcount", js.executeScript("return parseInt(arguments[0])", vars.get("newcount")));
    System.out.println("New count: "+vars.get("newcount").toString());
    assertEquals(vars.get("oldcount").toString(), vars.get("newcount").toString());
  }
  @Test
  public void writeBlogAsDraft() {
    driver.get("https://pikabu.ru/");
    mylogin();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[1]/div/div[1]/aside/div[2]/a[1]")));
    }
    driver.findElement(By.xpath("/html/body/div[1]/div/div[1]/aside/div[2]/a[1]")).click();
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div/div[1]/div[1]/button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[3]/div/div[1]/div/div[1]/div/button")));
    }
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    vars.put("oldcount", driver.findElements(By.xpath("//html/body/div[3]/div/div[1]/div/div[2]/div/div")).size());
    System.out.println("Old count: "+vars.get("oldcount").toString());
    vars.put("oldcount", js.executeScript("return parseInt(arguments[0])+1", vars.get("oldcount")));
    driver.findElement(By.xpath("//html/body/div[3]/div/div[1]/div/div[1]/div/button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div[1]/div[2]/main/div/div/div[1]/div[1]/div[3]/div/div/div/p")));
    }
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[2]/main/div/div/div[1]/div[1]/div[2]/textarea")).sendKeys("test");
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div/div[1]/div[2]/button[1]")).click();
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div/div[1]/div[1]/button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[3]/div/div[1]/div/div[1]/div/div/span")));
    }
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    vars.put("newcount", driver.findElements(By.xpath("//html/body/div[3]/div/div[1]/div/div[2]/div/div")).size());
    System.out.println("New count:" + vars.get("newcount").toString());
    vars.put("newcount", js.executeScript("return parseInt(arguments[0])", vars.get("newcount")));
    assertEquals(vars.get("newcount").toString(), vars.get("oldcount").toString());
  }
  @Test
  public void login() {
    driver.get("https://pikabu.ru/");
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[1]/div/div/input")));
    }
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[1]/div/div/input")).sendKeys("123");
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[2]/div/div/input")).sendKeys("123");
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[7]/button")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[5]/span"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[1]/div/div/input")).clear();
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[2]/div/div/input")).clear();
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[1]/div/div/input")).sendKeys("x1761270349@gmail.com");
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[2]/div/div/input")).sendKeys("password");
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/div[1]/div[2]/form/div[7]/button")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/a")));
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//html/body/div[1]/div[1]/div[1]/aside/div[1]/div[1]/div/a"));
      assert(elements.size() > 0);
    }
  }
}
